"""Odds API team name -> ESPN school name, the CFB live source's team key.

VERIFIED AGAINST THE ODDS API: every name below was seen in a live
americanfootball_ncaaf payload, collected from the committed legacy board
snapshots (data/cfb_divergence/*.json, both matched and unmatched names).
Their mapping to ESPN's spelling was produced by the legacy board's own
mascot-stripping matcher (deploy/cfb_odds_watch.map_odds_names_to_ratings),
checked against every pair that board had already priced -- no disagreement
-- and the six it could not resolve were added by hand, marked below.

The table is exact, like every other league's (execution/matching.py). A name
not listed is REFUSED and named, never stripped or guessed at; add it here
deliberately. The legacy matcher's history is why: its first version priced
Utah Tech with Utah's rating and manufactured a 42-point edge.
"""

from coverline.execution.matching import TeamTable

#: Hand-added (the matcher could not resolve them): Citadel, Grambling State,
#: Houston Baptist, Nicholls State, Sam Houston State, Southern Mississippi.
CFB_NAMES: dict[str, str] = {
    'Abilene Christian Wildcats': 'Abilene Christian',
    'Air Force Falcons': 'Air Force',
    'Alabama Crimson Tide': 'Alabama',
    'Alabama State Hornets': 'Alabama State',
    'Alcorn State Braves': 'Alcorn State',
    'Appalachian State Mountaineers': 'App State',
    'Arizona State Sun Devils': 'Arizona State',
    'Arizona Wildcats': 'Arizona',
    'Arkansas Razorbacks': 'Arkansas',
    'Arkansas State Red Wolves': 'Arkansas State',
    'Army Black Knights': 'Army',
    'Auburn Tigers': 'Auburn',
    'Austin Peay Governors': 'Austin Peay',
    'BYU Cougars': 'BYU',
    'Ball State Cardinals': 'Ball State',
    'Baylor Bears': 'Baylor',
    'Boise State Broncos': 'Boise State',
    'Boston College Eagles': 'Boston College',
    'Bowling Green Falcons': 'Bowling Green',
    'Bryant Bulldogs': 'Bryant',
    'Buffalo Bulls': 'Buffalo',
    'Cal Poly Mustangs': 'Cal Poly',
    'California Golden Bears': 'California',
    'Campbell Fighting Camels': 'Campbell',
    'Central Connecticut Blue Devils': 'Central Connecticut',
    'Central Michigan Chippewas': 'Central Michigan',
    'Charleston Southern Buccaneers': 'Charleston Southern',
    'Charlotte 49ers': 'Charlotte',
    'Cincinnati Bearcats': 'Cincinnati',
    'Citadel Bulldogs': 'The Citadel',
    'Clemson Tigers': 'Clemson',
    'Coastal Carolina Chanticleers': 'Coastal Carolina',
    'Colgate Raiders': 'Colgate',
    'Colorado State Rams': 'Colorado State',
    'Delaware Blue Hens': 'Delaware',
    'Delaware State Hornets': 'Delaware State',
    'Duke Blue Devils': 'Duke',
    'Duquesne Dukes': 'Duquesne',
    'East Carolina Pirates': 'East Carolina',
    'East Tennessee State Buccaneers': 'East Tennessee State',
    'East Texas A&M Lions': 'East Texas A&M',
    'Eastern Kentucky Colonels': 'Eastern Kentucky',
    'Eastern Michigan Eagles': 'Eastern Michigan',
    'Eastern Washington Eagles': 'Eastern Washington',
    'Florida A&M Rattlers': 'Florida A&M',
    'Florida Atlantic Owls': 'Florida Atlantic',
    'Florida Gators': 'Florida',
    'Florida International Panthers': 'Florida International',
    'Florida State Seminoles': 'Florida State',
    'Fordham Rams': 'Fordham',
    'Fresno State Bulldogs': 'Fresno State',
    'Furman Paladins': 'Furman',
    'Gardner-Webb Runnin Bulldogs': 'Gardner-Webb',
    'Georgia Bulldogs': 'Georgia',
    'Georgia Southern Eagles': 'Georgia Southern',
    'Georgia State Panthers': 'Georgia State',
    'Grambling State Tigers': 'Grambling',
    'Hampton Pirates': 'Hampton',
    'Hawaii Rainbow Warriors': "Hawai'i",
    'Houston Baptist Huskies': 'Houston Christian',
    'Houston Cougars': 'Houston',
    'Idaho State Bengals': 'Idaho State',
    'Illinois Fighting Illini': 'Illinois',
    'Illinois State Redbirds': 'Illinois State',
    'Indiana Hoosiers': 'Indiana',
    'Iowa Hawkeyes': 'Iowa',
    'Iowa State Cyclones': 'Iowa State',
    'Jacksonville State Gamecocks': 'Jacksonville State',
    'James Madison Dukes': 'James Madison',
    'Kansas Jayhawks': 'Kansas',
    'Kansas State Wildcats': 'Kansas State',
    'Kennesaw State Owls': 'Kennesaw State',
    'Kent State Golden Flashes': 'Kent State',
    'Kentucky Wildcats': 'Kentucky',
    'LSU Tigers': 'LSU',
    'Lafayette Leopards': 'Lafayette',
    'Lamar Cardinals': 'Lamar',
    'Liberty Flames': 'Liberty',
    'Louisiana Ragin Cajuns': 'Louisiana',
    'Louisiana Tech Bulldogs': 'Louisiana Tech',
    'Louisville Cardinals': 'Louisville',
    'Maine Black Bears': 'Maine',
    'Marshall Thundering Herd': 'Marshall',
    'Maryland Terrapins': 'Maryland',
    'Memphis Tigers': 'Memphis',
    'Mercyhurst Lakers': 'Mercyhurst',
    'Miami (OH) RedHawks': 'Miami (OH)',
    'Miami Hurricanes': 'Miami',
    'Michigan State Spartans': 'Michigan State',
    'Michigan Wolverines': 'Michigan',
    'Middle Tennessee Blue Raiders': 'Middle Tennessee',
    'Mississippi State Bulldogs': 'Mississippi State',
    'Mississippi Valley State Delta Devils': 'Mississippi Valley State',
    'Missouri State Bears': 'Missouri State',
    'Missouri Tigers': 'Missouri',
    'Montana Grizzlies': 'Montana',
    'Morgan State Bears': 'Morgan State',
    'Murray State Racers': 'Murray State',
    'Navy Midshipmen': 'Navy',
    'Nebraska Cornhuskers': 'Nebraska',
    'Nevada Wolf Pack': 'Nevada',
    'New Mexico Lobos': 'New Mexico',
    'New Mexico State Aggies': 'New Mexico State',
    'Nicholls State Colonels': 'Nicholls',
    'North Carolina Tar Heels': 'North Carolina',
    'North Dakota State Bison': 'North Dakota State',
    'North Texas Mean Green': 'North Texas',
    'Northern Arizona Lumberjacks': 'Northern Arizona',
    'Northern Illinois Huskies': 'Northern Illinois',
    'Northwestern State Demons': 'Northwestern State',
    'Northwestern Wildcats': 'Northwestern',
    'Notre Dame Fighting Irish': 'Notre Dame',
    'Ohio Bobcats': 'Ohio',
    'Ohio State Buckeyes': 'Ohio State',
    'Oklahoma Sooners': 'Oklahoma',
    'Oklahoma State Cowboys': 'Oklahoma State',
    'Old Dominion Monarchs': 'Old Dominion',
    'Ole Miss Rebels': 'Ole Miss',
    'Oregon Ducks': 'Oregon',
    'Oregon State Beavers': 'Oregon State',
    'Penn State Nittany Lions': 'Penn State',
    'Pittsburgh Panthers': 'Pittsburgh',
    'Portland State Vikings': 'Portland State',
    'Rutgers Scarlet Knights': 'Rutgers',
    'SMU Mustangs': 'SMU',
    'Sacramento State Hornets': 'Sacramento State',
    'Sam Houston State Bearkats': 'Sam Houston',
    'South Alabama Jaguars': 'South Alabama',
    'South Carolina Gamecocks': 'South Carolina',
    'South Dakota State Jackrabbits': 'South Dakota State',
    'South Florida Bulls': 'South Florida',
    'Southern Mississippi Golden Eagles': 'Southern Miss',
    'Stanford Cardinal': 'Stanford',
    'TCU Horned Frogs': 'TCU',
    'Temple Owls': 'Temple',
    'Tennessee Volunteers': 'Tennessee',
    'Texas A&M Aggies': 'Texas A&M',
    'Texas Longhorns': 'Texas',
    'Texas State Bobcats': 'Texas State',
    'Tulane Green Wave': 'Tulane',
    'Tulsa Golden Hurricane': 'Tulsa',
    'UAB Blazers': 'UAB',
    'UCF Knights': 'UCF',
    'UCLA Bruins': 'UCLA',
    'UConn Huskies': 'UConn',
    'UL Monroe Warhawks': 'UL Monroe',
    'UNLV Rebels': 'UNLV',
    'USC Trojans': 'USC',
    'UTEP Miners': 'UTEP',
    'Virginia Cavaliers': 'Virginia',
    'Virginia Tech Hokies': 'Virginia Tech',
    'Wake Forest Demon Deacons': 'Wake Forest',
    'Washington Huskies': 'Washington',
    'Washington State Cougars': 'Washington State',
    'West Virginia Mountaineers': 'West Virginia',
    'Western Kentucky Hilltoppers': 'Western Kentucky',
    'Western Michigan Broncos': 'Western Michigan',
    'Wisconsin Badgers': 'Wisconsin',
    'Wyoming Cowboys': 'Wyoming',
    # ADDED 2026-09-25 from the first live capture's payload, where each was
    # refused by name. Every target was checked to exist EXACTLY in ESPN's
    # 2026 school names (data/raw/cfb/espn_2026.parquet) -- no stripping.
    'Akron Zips': 'Akron',
    'Bucknell Bison': 'Bucknell',
    'Central Arkansas Bears': 'Central Arkansas',
    'Colorado Buffaloes': 'Colorado',
    'Georgia Tech Yellow Jackets': 'Georgia Tech',
    'Howard Bison': 'Howard',
    'Incarnate Word Cardinals': 'Incarnate Word',
    'LIU Sharks': 'Long Island University',
    'Lindenwood Lions': 'Lindenwood',
    'Minnesota Golden Gophers': 'Minnesota',
    'NC State Wolfpack': 'NC State',
    'North Carolina Central Eagles': 'North Carolina Central',
    'Purdue Boilermakers': 'Purdue',
    'Rice Owls': 'Rice',
    'Robert Morris Colonials': 'Robert Morris',
    'Stonehill Skyhawks': 'Stonehill',
    'Texas Tech Red Raiders': 'Texas Tech',
    'Toledo Rockets': 'Toledo',
    'UMass Minutemen': 'Massachusetts',
    'UTSA Roadrunners': 'UTSA',
    'Utah State Aggies': 'Utah State',
    'Utah Utes': 'Utah',
    'Vanderbilt Commodores': 'Vanderbilt',
    'William and Mary Tribe': 'William & Mary',
    'San Diego State Aztecs': 'San Diego State',
    'Troy Trojans': 'Troy',
}

TABLE = TeamTable("cfb", CFB_NAMES, verified_against_odds_api=True)
