#!/usr/bin/env bash
# Install the git hooks that make a red commit hard rather than merely
# discouraged.
#
# WHY THIS EXISTS
# scripts/check.sh has documented a pre-commit hook since it was written, and
# nobody installed it. On 2026-09-21 a commit went out with a failing test
# because the command that was supposed to gate it piped check.sh into grep,
# and grep exits 0 when it FINDS lines -- including the line reporting a
# failure. The gate was reporting success on evidence of failure.
#
# Discipline had one job and did it wrong. This is the structural version.
#
# The hook runs check.sh and refuses the commit on a non-zero exit. It is
# bypassable with `git commit --no-verify`, which is correct: a hook that
# cannot be bypassed gets uninstalled the first time it is wrong.
#
#   bash scripts/install_hooks.sh
#
# .git/hooks/ is not tracked by git, so this has to be run once per clone.
set -euo pipefail
cd "$(dirname "$0")/.."

HOOK=".git/hooks/pre-commit"
mkdir -p .git/hooks

cat > "$HOOK" <<'HOOK_EOF'
#!/usr/bin/env bash
# Generated by scripts/install_hooks.sh -- re-run that to update.
#
# Runs the full suite before every commit and refuses on failure. Uses the
# EXIT CODE, never the output: a check whose success condition is "some text
# appeared" is not a check.
set -uo pipefail
repo="$(git rev-parse --show-toplevel)"

# Prefer the project venv, which is where the pinned interpreter and the
# declared dependencies live. Without it check.sh exits 2 (not verified),
# which is different from failure and must not block a commit.
if [ -x "$repo/.venv/bin/python" ]; then
  PATH="$repo/.venv/bin:$PATH"
  export PATH
fi

out="$(bash "$repo/scripts/check.sh" 2>&1)"
rc=$?

if [ $rc -eq 2 ]; then
  echo "$out" | tail -4
  echo
  echo "pre-commit: environment incomplete, so nothing was verified."
  echo "  This is NOT the same as a failure and is not blocking the commit."
  echo "  fix: python3 -m venv .venv && .venv/bin/pip install -r requirements.txt"
  exit 0
fi

if [ $rc -ne 0 ]; then
  echo "$out" | grep -E "FAILED|failed|\^ FAILED|CHECKS FAILED" | head -20
  echo
  echo "pre-commit: the suite failed, so this commit is refused."
  echo "  See the full output with: bash scripts/check.sh"
  echo "  To commit anyway (and you should have a reason): git commit --no-verify"
  exit 1
fi

echo "pre-commit: all checks passed"
exit 0
HOOK_EOF

chmod +x "$HOOK"
echo "installed $HOOK"
echo
echo "It runs scripts/check.sh and refuses a commit on failure, keyed on the"
echo "EXIT CODE. Bypass with --no-verify when you have a reason."
