#!/usr/bin/env python3
"""Enumerate every test in the repo, so a suite cannot silently shrink.

WHY THIS EXISTS
---------------
Two guard tests were once lost to a cherry-pick that resolved a test file by
taking the incoming version wholesale. Nothing announced it. The suite simply
reported a smaller number that still said "all passed", and a count nobody
compares is not a check.

There is no standard tool for this. pytest's exit code 5 (no tests collected)
catches only the total wipeout, and coverage ratcheting guards against new
untested code rather than deleted tests -- a different failure. So: a checked-in
manifest, regenerated and diffed in CI, which names WHICH test disappeared
rather than just reporting a smaller number.

The manifest deliberately spans both test styles in this repo -- the pytest
suites under tests/core/ and the legacy plain-python suites that define test_
functions and are run directly -- because the tests that went missing were in
the legacy style, and a manifest that covered only pytest would have missed
exactly the failure it is named after.

Usage:
    python3 tools/test_manifest.py            # print the manifest
    python3 tools/test_manifest.py --write    # rewrite tests/MANIFEST.txt
    python3 tools/test_manifest.py --check    # exit 1 if it differs
"""

from __future__ import annotations

import argparse
import ast
import importlib.util
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
MANIFEST = ROOT / "tests" / "MANIFEST.txt"

#: Suites that are plain python scripts, not pytest modules.
LEGACY_SUITES = ("tests/test_model_guards.py", "tests/test_parsers.py")


class CollectionUnavailable(RuntimeError):
    """Collection could not run at all -- NOT the same as tests being gone."""


def pytest_tests() -> list[str]:
    """Ask pytest what it can collect under tests/core/.

    FAILS CLOSED. The first version of this function returned [] whenever
    pytest was missing or collection errored, which made the tool report every
    pytest test as DISAPPEARED on any machine without pytest installed -- a
    false alarm indistinguishable from the real thing. A detector that cannot
    tell "deleted" from "could not look" is worse than no detector: it trains
    you to ignore it, and the one time it is right you will.

    Found by running the tool on the desktop, which has no pytest. It claimed
    82 tests had vanished.
    """
    if importlib.util.find_spec("pytest") is None:
        raise CollectionUnavailable(
            "pytest is not installed, so the test inventory cannot be read.\n"
            "  This is an ENVIRONMENT problem, not a missing-test problem.\n"
            "  fix:  pip install -r requirements.txt"
        )

    proc = subprocess.run(
        [sys.executable, "-m", "pytest", "tests/core", "--collect-only", "-q",
         "--no-header", "-p", "no:cacheprovider"],
        cwd=ROOT, capture_output=True, text=True,
    )
    # pytest exit codes: 0 = collected, 5 = collected nothing, others = error.
    if proc.returncode not in (0, 5):
        raise CollectionUnavailable(
            f"pytest collection exited {proc.returncode}; the inventory is "
            f"unreadable, so no conclusion about missing tests is possible.\n"
            f"  stderr: {proc.stderr.strip()[:400]}"
        )

    out = []
    for line in proc.stdout.splitlines():
        line = line.strip()
        if "::" in line and not line.startswith(("=", "_", "[")):
            out.append(line.split(" ")[0])

    if proc.returncode == 0 and not out:
        raise CollectionUnavailable(
            "pytest reported success but named no tests; refusing to treat an "
            "unparseable collection as an empty suite"
        )
    return out


def legacy_tests() -> list[str]:
    """Parse test_ functions out of the plain-python suites without importing
    them -- importing would run their module-level setup."""
    out = []
    for rel in LEGACY_SUITES:
        path = ROOT / rel
        if not path.exists():
            continue
        tree = ast.parse(path.read_text())
        for node in tree.body:
            if isinstance(node, ast.FunctionDef) and node.name.startswith("test_"):
                out.append(f"{rel}::{node.name}")
    return out


def build() -> str:
    names = sorted(set(pytest_tests()) | set(legacy_tests()))
    header = [
        "# Generated by tools/test_manifest.py -- do not hand-edit.",
        "# A test disappearing from this list is a CI failure that NAMES it.",
        "# Regenerate deliberately with: python3 tools/test_manifest.py --write",
        f"# count: {len(names)}",
    ]
    return "\n".join(header + names) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--write", action="store_true")
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()

    try:
        current = build()
    except CollectionUnavailable as exc:
        # Exit 2, matching scripts/check.sh: not verified is not the same as
        # broken, and saying so keeps this from crying wolf.
        print(f"INVENTORY UNAVAILABLE -- {exc}", file=sys.stderr)
        return 2

    if args.write:
        MANIFEST.parent.mkdir(parents=True, exist_ok=True)
        MANIFEST.write_text(current)
        print(f"wrote {MANIFEST.relative_to(ROOT)} ({current.count(chr(10)) - 4} tests)")
        return 0

    if args.check:
        if not MANIFEST.exists():
            print("MANIFEST.txt is missing; run: python3 tools/test_manifest.py --write")
            return 1
        recorded = MANIFEST.read_text()
        if recorded == current:
            return 0
        rec = {l for l in recorded.splitlines() if not l.startswith("#")}
        cur = {l for l in current.splitlines() if not l.startswith("#")}
        gone, added = sorted(rec - cur), sorted(cur - rec)
        if gone:
            print(f"TESTS DISAPPEARED ({len(gone)}):")
            for t in gone:
                print(f"  - {t}")
        if added:
            print(f"tests added ({len(added)}):")
            for t in added:
                print(f"  + {t}")
        print("\nIf the removals were intended, rerun with --write and commit.")
        return 1

    print(current, end="")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
